app = "sartarosh-bot"
primary_region = "ams"

[env]
  NODE_ENV = "production"

[build]
  # Agar Dockerfile bo'lsa Fly o'zi topadi, bo'lmasa o'zi quradi


[[mounts]]
  source = "bot_data"
  destination = "/data"